export const ERROR = 'ERROR';

//GET LOGIN
export const GET_LOGIN_BEGIN = 'GET_LOGIN_BEGIN';
export const GET_LOGIN_FOUND = 'GET_LOGIN_FOUND';
export const GET_LOGIN_NOT_FOUND = 'GET_LOGIN_NOT_FOUND';
export const ERROR_GET_LOGIN_IN = 'ERROR_GET_LOGIN_IN';
export const ERROR_GET_LOGIN_BLANK = 'ERROR_GET_LOGIN_BLANK';

//DO LOGIN
export const DO_LOGIN_BEGIN = 'DO_LOGIN_BEGIN';
export const DO_LOGIN_VALID = 'DO_LOGIN_VALID';
export const DO_LOGIN_NOT_VALID = 'DO_LOGIN_NOT_VALID';
export const ERROR_DO_LOGIN = 'ERROR_DO_LOGIN';

//DO LOGOUT
export const DO_LOGOUT_BEGIN = 'DO_LOGOUT_BEGIN';
export const DO_LOGOUT_SUCCESS = 'DO_LOGOUT_SUCCESS';
export const ERROR_DO_LOGOUT = 'ERROR_DO_LOGOUT';

//GET AND FILTER WORK ORDERS
export const GET_WORK_ORDERS_BEGIN = 'GET_WORK_ORDERS_BEGIN';
export const GET_WORK_ORDERS_SUCCESS = 'GET_WORK_ORDERS_SUCCESS';
export const SET_WORK_ORDERS_ALL = 'SET_WORK_ORDERS_ALL';
export const FILTER_WORK_ORDERS_BEGIN = 'FILTER_WORK_ORDERS_BEGIN';
export const SET_WORK_ORDERS_OPEN = 'SET_WORK_ORDERS_OPEN';
export const SET_WORK_ORDERS_IN_PROGRESS = 'SET_WORK_ORDERS_IN_PROGRESS';
export const SET_WORK_ORDERS_CLOSED = 'SET_WORK_ORDERS_CLOSED';
export const SET_WORK_ORDERS_CANCELLED = 'SET_WORK_ORDERS_CANCELLED';
export const SET_WORK_ORDERS_FINALIZED = 'SET_WORK_ORDERS_FINALIZED';
export const FILTER_WORK_ORDERS_SUCCESS = 'FILTER_WORK_ORDERS_SUCCESS';
export const ERROR_GET_AND_FILTER_WORK_ORDERS = 'ERROR_GET_AND_FILTER_WORK_ORDERS';

//GET PROCESS WORK ORDER
export const GET_PROCESS_WORK_ORDER_BEGIN = 'GET_PROCESS_WORK_ORDER_BEGIN';
export const SET_PROCESS_WORK_ORDER = 'SET_PROCESS_WORK_ORDER';
export const GET_PROCESS_WORK_ORDER_TEMP_REPORT = 'GET_PROCESS_WORK_ORDER_TEMP_REPORT';
export const GET_PROCESS_WORK_ORDER_SUCCESS = 'GET_PROCESS_WORK_ORDER_SUCCESS';
export const ERROR_GET_PROCESS_WORK_ORDER = 'ERROR_GET_PROCESS_WORK_ORDER';

//DO CHECK IN
export const DO_CHECK_IN_BEGIN = 'DO_CHECK_IN_BEGIN';
export const DO_CHECK_IN_SUCCESS = 'DO_CHECK_IN_SUCCESS';
export const ERROR_DO_CHECK_IN = 'ERROR_DO_CHECK_IN';

//DO CHECK OUT
export const DO_CHECK_OUT_BEGIN = 'DO_CHECK_OUT_BEGIN';
export const DO_CHECK_OUT_SUCCESS = 'DO_CHECK_OUT_SUCCESS';
export const ERROR_DO_CHECK_OUT = 'ERROR_DO_CHECK_OUT';

//CANCEL WORK ORDER
export const CANCEL_WORK_ORDER_BEGIN = 'CANCEL_WORK_ORDER_BEGIN';
export const CANCEL_WORK_ORDER_SUCCESS = 'CANCEL_WORK_ORDER_SUCCESS';
export const ERROR_CANCEL_WORK_ORDER = 'ERROR_CANCEL_WORK_ORDER';

//FINALIZE WORK ORDER
export const FINALIZE_WORK_ORDER_BEGIN = 'FINALIZE_WORK_ORDER_BEGIN';
export const FINALIZE_WORK_ORDER_SUCCESS = 'FINALIZE_WORK_ORDER_SUCCESS';
export const ERROR_FINALIZE_WORK_ORDER = 'ERROR_FINALIZE_WORK_ORDER';